	
SQLLDR 4G/root control=_4G_DM_V_M_CUS_CB_HOR_MOBILE.CTL log=log.txt bad=bad.txt 
SQLLDR 4G/root control=_4G_DWA_V_M_4G_VOICE_BEHAVIOR_079.CTL log=log.txt bad=bad.txt 
SQLLDR 4G/root control=_4G_DWD_M_RES_MB_TERMINAL_IMEI.CTL log=log.txt bad=bad.txt 
SQLLDR 4G/root control=_4G_DYL_4G_DEV_NUM_SHANG.CTL log=log.txt bad=bad.txt 
SQLLDR 4G/root control=_4G_VIEW_IMEI_TAC_INFO.CTL log=log.txt bad=bad.txt 
