	
SQLLDR 3G/root control=_3G_DIM_BI_SUBS_GROUP_TYPE.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWA_S_M_ACC_AL_PAY_079.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWA_V_M_3G_VOICE_BEHAVIOR_079.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWA_V_M_CUS_3G_HOR_MOBILE_079.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWA_V_M_CUS_AL_ORD_MEMBER_079.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWA_V_M_CUS_MB_SI_IMEI_IF_079.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DWD_M_RES_MB_TERMINAL_IMEI.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_DYL_3G_DEV_NUM_SHANG.CTL log=log.txt bad=bad.txt 
SQLLDR 3G/root control=_3G_VIEW_IMEI_TAC_INFO.CTL log=log.txt bad=bad.txt 
